server:
  port: 8080

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
      routes:
        - id: USER-DATA
          uri: lb://USER-DATA
          predicates:
            - Path=/api/v1/**
          filters:
            - JwtAuthFilter


        - id: PRODUCT-STORE
          uri: lb://PRODUCT-STORE
          predicates:
            - Path=/product/**
          filters:
            - JwtAuthFilter
        - id: CONTACT-REQUESTS
          uri: lb://CONTACT-REQUESTS
          predicates:
            - Path=/contact/**
          filters:
            - JwtAuthFilter
        - id: ORDERS-DATA
          uri: lb://ORDERS-DATA
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthFilter
        - id: REVIEWS
          uri: lb://REVIEWS
          predicates:
            - Path=/reviews/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}